#!/usr/bin/env python3
"""
Quick test post to verify the system is working
"""

import os
import pickle
from datetime import datetime
from googleapiclient.discovery import build
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def create_test_post():
    """Create a simple test post"""
    
    # Check OAuth credentials
    if not os.path.exists('token.pickle'):
        print("❌ No OAuth token found. Run simple_oauth.py first.")
        return False
    
    with open('token.pickle', 'rb') as token:
        creds = pickle.load(token)
    
    if not creds or not creds.valid:
        print("❌ OAuth credentials invalid")
        return False
    
    # Create test content
    current_time = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    
    title = f"✅ System Test - {current_time}"
    content = f"""
    <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2>🧪 DailyMuse System Test</h2>
        
        <p>This is a <strong>system test</strong> created on {current_time}.</p>
        
        <h3>✅ Status Check:</h3>
        <ul>
            <li>🔐 OAuth Authentication: <span style="color: green;"><strong>Working</strong></span></li>
            <li>📡 Blogger API Connection: <span style="color: green;"><strong>Active</strong></span></li>
            <li>🤖 Automated Posting: <span style="color: green;"><strong>Functional</strong></span></li>
        </ul>
        
        <blockquote style="border-left: 4px solid #007acc; padding-left: 20px; margin: 20px 0; font-style: italic; color: #555;">
            "Your automated blogging system is ready for daily content generation!" 🚀
        </blockquote>
        
        <p>Next step: Enable daily automation with GitHub Actions.</p>
        
        <hr style="margin: 30px 0; border: none; border-top: 2px solid #eee;">
        <p style="text-align: center; color: #888; font-size: 14px;">
            <em>Auto-generated by DailyMuse System Test</em>
        </p>
    </div>
    """
    
    # Post to Blogger
    try:
        service = build('blogger', 'v3', credentials=creds)
        blog_id = "6516028868152229433"  # Your DailyMuse blog ID
        
        post_data = {
            'kind': 'blogger#post',
            'title': title,
            'content': content
        }
        
        print("🚀 Creating test post...")
        result = service.posts().insert(blogId=blog_id, body=post_data).execute()
        
        post_url = result.get('url', 'Unknown URL')
        print(f"✅ Test post created successfully!")
        print(f"🔗 URL: {post_url}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating test post: {e}")
        return False

if __name__ == "__main__":
    print("🧪 Running DailyMuse System Test")
    print("=" * 40)
    
    success = create_test_post()
    
    if success:
        print("\n🎉 SYSTEM TEST PASSED!")
        print("✅ Your automated blogging system is fully operational")
        print("🚀 Ready for daily automation!")
    else:
        print("\n❌ SYSTEM TEST FAILED")
        print("Please check the error messages above")
