name: Daily AI Blog Generation

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials and token files
      env:
        CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        TOKEN_PICKLE_B64: ${{ secrets.GOOGLE_TOKEN_PICKLE_B64 }}
      run: |
        echo "$CREDENTIALS_JSON" > credentials.json
        echo "$TOKEN_PICKLE_B64" | base64 -d > token.pickle
    
    - name: Generate and post blog automatically
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
      run: |
        python oauth_blogger_bot.py
    
    - name: Log completion
      run: |
        echo "✅ Automated blog posting completed at $(date)"
        echo "🌐 Check your blog at: https://dailymuset.blogspot.com"
