name: Daily AI Blog Generation

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r auto-medium-blog/requirements.txt
    
    - name: Generate Medium-ready blog post
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python medium_ready_bot.py
    
    - name: Upload generated blog post
      uses: actions/upload-artifact@v4
      with:
        name: medium-ready-post
        path: medium_post_*.md
        retention-days: 30
    
    - name: Log completion
      run: |
        echo "Blog generation completed at $(date)"
        echo "Download the generated post from the Actions artifacts"
        echo "Then manually post it to Medium at https://medium.com/new-story"
